petstagram/photos/urls.py
from django.urls import path, include
from .views import photo_add, photo_details, photo_edit, photo_delete

urlpatterns = [
    # photos/
    path('add/', photo_add, name='photo add'),
    path('<int:pk>/', include([
        path('', photo_details, name='photo details'),
        path('edit/', photo_edit, name='photo edit'),
        path('delete/', photo_delete, name='photo delete'),
    ]))
]

petstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("petstagram.common.urls")),
    path('accounts/', include("petstagram.accounts.urls")),
    path('pets/', include("petstagram.pets.urls")),
    path('photos/', include("petstagram.photos.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/photos/models.py
# photos app - models
from django.db import models
from django.core.validators import MinLengthValidator
from .validators import image_size_validator_5mb, text_underscore_validator

from petstagram.pets.models import Pet

# Create your models here.

"""
The field Photo is required:
• Photo - the user can upload a picture from storage, the maximum size of the photo can be 5MB
The fields description and tagged pets are optional:
• Description - a user can write any description of the photo;
 it should consist of a maximum of 300 characters
and a minimum of 10 characters
• Location - it should consist of a maximum of 30 characters
• Tagged Pets - the user can tag none, one, or many of all pets.
 There is no limit on the number of tagged pets
There should be created one more field that will be automatically generated:
• Date of publication - when a picture is added or edited,
 the date of publication is automatically generated
"""


class Photo(models.Model):
    pet_image = models.ImageField(
        blank=False,
        null=False,
        validators=(image_size_validator_5mb,),
        upload_to="photos"
    )
    # optional
    description = models.TextField(
        max_length=300,
        validators=(MinLengthValidator(10), text_underscore_validator,),
        blank=True,
        null=True
    )
    location = models.CharField(max_length=30, blank=True, null=True)
    tagged_pets = models.ManyToManyField(Pet, blank=True)
    date_of_publication = models.DateField(auto_now=True)


    def __str__(self):
        return f"{self.pk} - {self.pet_image}"

petstagram/photos/forms.py
from django import forms
from .models import Photo

labels = {
    'pet_image': 'Photo file',
    'description': 'Description',
    'location': 'Location',
    'tagged_pets': 'Tag Pets'
}


class PhotoAddForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['pet_image', 'description', 'location', 'tagged_pets']
        labels = labels


class PhotoEditForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['description', 'location', 'tagged_pets']
        exclude = ['pet_image']
        labels = labels



class ExampleForm(forms.Form):
    description = forms.CharField(
        validators=[text_underscore_validator]
    )


# 1. full_clean
# 2. clean fields
# 3. field -> clean
# 4. run validators
# 5. validator(value)

petstagram/photos/views.py
from django.shortcuts import render, redirect
from petstagram.common.forms import CommentForm
from .forms import PhotoAddForm, PhotoEditForm
from .models import Photo


# Create your views here.

def photo_add(request):
    form = PhotoAddForm()

    if request.method == "POST":
        form = PhotoAddForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')

    context = {
        "form": form,
    }

    return render(request, 'photos/photo-add-page.html', context=context)


def photo_details(request, pk):
    photo = Photo.objects.get(pk=pk)
    comment_form = CommentForm()

    context = {
        "photo": photo,
        "likes": photo.like_set.count(),
        "comments": photo.comment_set.all(),
        "comment_form": comment_form,
    }

    return render(
        request,
        'photos/photo-details-page.html',
        context=context
    )


def photo_edit(request, pk):
    photo = Photo.objects.get(pk=pk)
    form = PhotoEditForm(instance=photo)

    if request.method == "POST":
        form = PhotoEditForm(request.POST, instance=photo)
        if form.is_valid():
            form.save()
            return redirect('photo details', pk=pk)

    context = {
        "photo": photo,
        "form": form,
    }

    return render(request, 'photos/photo-edit-page.html', context)


def photo_delete(request, pk):
    photo = Photo.objects.get(pk=pk)
    photo.delete()
    return redirect('index')

templates/photos/photo-add-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

templates/photos/photo-details-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <div class="container">
        <div class="col-9">

            <!-- Start Pet Photo Post Section -->
            <div class="card">
                <div class="top">

                    <!-- Start User Details and Image Location Section -->
                    <div class="userDetails">

                        <!-- Link to User Profile Details Page-->
                        <a href="#">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="/images/person.png" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>

                            <!-- Link to User Profile Details Page -->
                            <a href="#">
                                <!-- IF user has first name and last name -->
                                Diyan Kalaydzhiev
                                <!-- else -->
                                <!-- show user username -->
                            </a>
                            <br>

                            <!-- IF the photo has location -->
                            <span>Bansko, Bulgaria</span>

                            <!-- IF the viewer is the creator of the photo -->
                            <div class="edit-delete-btns">

                                <!-- Link to Edit Pet Photo Page -->
                                <a href="#">
                                    <img class="edit-img" src="/images/edit-pen-icon-6.jpg"
                                         alt="edit button">
                                </a>

                                <!-- Link to Delete Pet Photo Page -->
                                <a href="#">
                                    <img class="bin-img" src="/images/icon-remove-22.jpg" alt="bin button">
                                </a>
                            </div>
                            <!-- End IF the viewer is the creator of the photo -->

                        </h3>
                    </div>
                    <!-- End User Details and Image Location Section -->

                </div>

                <!-- Start Pet Photo -->
                <div class="imgBx" id="place the id of the photo here">
                    <!-- Pet Photo -->
                    <img src="/images/axolotl.jpeg" alt="post" class="cover">
                </div>
                <!-- End Pet Photo -->

                <div class="bottom">

                    <!-- Start Like and Share Buttons Section -->
                    <div class="actionBtns">
                        <div class="left">

                            <!-- Start Like Button -->
                            <span class="heart">

                                    <!-- Link to Like Path -->
									<a href="#">

										<!-- IF user has liked the photo -->
                                        <svg style="color: red"
                                             xmlns="http://www.w3.org/2000/svg"
                                             width="24"
                                             height="24"
                                             fill="currentColor"
                                             class="bi bi-heart-fill"
                                             viewBox="0 0 16 16">
                                            <!-- Coordinate path -->
                                            <path fill-rule="evenodd"
                                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                                  fill="red">
                                            </path>
                                        </svg>

                                        <!-- IF NOT user has liked the photo -->
                                        <svg aria-label="Like"
                                             color="#262626"
                                             fill="#262626"
                                             height="24"
                                             role="img"
                                             viewBox="0 0 48 48"
                                             width="24">
                                        <!-- Coordinate path -->
                                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                        </path>
                                        </svg>
								    </a>
                            </span>
                            <!-- End Like Button -->

                            <!-- Start Share  Button -->

                            <!-- Link to Share Path -->
                            <a href="#">
                                <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626"
                                     height="24" role="img" viewBox="0 0 48 48" width="24">
                                    <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
										3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
										1 1.2 1.1h.2c.5 0 1-.3
										1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
										6.1h35.5L18 18.7 5.2 6.1zm18.7
										33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                                    </path>
                                </svg>
                            </a>
                        </div>
                    </div>
                    <!-- End Like and Share Buttons Section -->

                    <!-- Number of Likes for the Photo -->
                    <p class="likes">203 likes</p>

                    <!-- Start Tagged Pets Section-->
                    <!-- Link to First Tagged Pet Details Page -->
                    <a href="#">
                        <p class="message">
                            <b>Sasho</b>
                        </p>
                    </a>
                    <!-- Link to Second Tagged Pet Details Page -->
                    <a href="#">
                        <p class="message">
                            <b>Some other fish</b>
                        </p>
                    </a>
                    <!-- End Tagged Pets Section-->

                    <!-- Photo description -->
                    <p class="pet-details">This is my pet</p>

                    <!-- Date of Publication or edit of the Photo -->
                    <h5 class="postTime">19/09/2022</h5>

                    <!-- Start Comments Section -->
                    <div class="comments">
                        <div class="top">
                            <div class="userDetails">
                                <div class="comment-data">
                                    <div class="profilepic">
                                        <div class="profile_img">
                                            <div class="image">
                                                <!-- User Profile Image -->
                                                <img src="/images/person.png" alt="img8">
                                            </div>
                                        </div>
                                    </div>
                                    <p>
                                        <!-- Link to User Profile Details Page-->
                                        <!-- User First and/or Last Name or username-->
                                        <a href="">Steven Ivanov</a>
                                        <!-- User Comment -->
                                        - OMG where can i get one
                                    </p>
                                </div>
                                <span>Sept. 20, 2022, 5:02 p.m.</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Comments Section -->
                </div>

                <!-- Start Add Comments Section -->
                <div class="addComments">
                    <div class="reaction">
                        <h3>
                            <i class="far fa-smile"></i>
                        </h3>
                    </div>

                    <!-- Start Add Comments Form -->
                    <form method="post" action="#">
                        <label for="id_body">Body:</label>
                        <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                  required="" id="id_body"></textarea>
                        <!-- Post Comments Button -->
                        <button type="submit">Post</button>
                    </form>
                    <!-- End Add Comments Form -->

                </div>
                <!-- End Add Comments Section -->

            </div>
            <!-- End Pet Photo Post Section -->

        </div>
    </div>

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

templates/photos/photo-edit-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>